version: '3'
services:
  resolver-simple:
    image: asia-northeast3-docker.pkg.dev/heekkr/heekkr-docker/heekkr-resolver-simple:main
    environment:
      KAKAO_API_KEY: ${KAKAO_API_KEY}
    expose:
      - 50051
    ports:
      - 50051:50051
