name: Build docker image and Deploy to Artifact Registry

on: push

env:
  IMAGE: asia-northeast3-docker.pkg.dev/heekkr/heekkr-docker/heekkr-api

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCP_WIF_PROVIDER }}"
          service_account: "${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}"

      - name: Build and Push
        env:
          ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        run: |
          gradle jib \
            -Djib.auth.username=oauth2accesstoken \
            -Djib.auth.password=$ACCESS_TOKEN \
            -Djib.container.environment=SPRING_PROFILES_ACTIVE="prod" \
            -Djib.to.tags=$GITHUB_REF_NAME,$GITHUB_SHA

  deploy:
    if: github.ref_name == 'main'
    permissions:
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    needs:
      - build
    steps:
      - name: Google Auth
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "${{ secrets.GCP_WIF_PROVIDER }}"
          service_account: "${{ secrets.GCP_WIF_SERVICE_ACCOUNT_RUN_DEPLOY }}"

      - id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: api
          image: "${{ env.IMAGE }}:main"
          region: asia-northeast3

      - name: Endpoint
        run: 'curl "${{ steps.deploy.outputs.url }}"'
